/*
 * vlhe_conf_template.c - see vlhe_conf_template.h.
 *
 * Copyright (c) 2026 Thomas Tranter
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Part of VLHE. See LICENSE for the full license text.
 *
 * THE COMMENT TEXT IS design/vsound.conf.example's. Edit it here and
 * there together; they are the same document in two forms.
 *
 * C89, GCC 2.95.2.
 */

#include <stdio.h>
#include <string.h>

#include "vlhe_conf_template.h"

/* ------------------------------------------------------------------ */
/* The file headers                                                   */
/* ------------------------------------------------------------------ */

static const char header_system[] =
";\n"
"; vlhe.conf - the machine's settings.\n"
";\n"
"; GENERATED. The control centre writes this file, and a new version\n"
"; replaces it wholesale - so a comment added by hand will not survive.\n"
"; Edit the values freely; they are read back as written.\n"
";\n"
"; THE FILE DESCRIBES INTENT. Something else - the init script, or a\n"
"; launcher - translates it into module parameters and command-line\n"
"; arguments. The daemons keep the syntax they already have.\n"
";\n"
"; Every value is the CURRENT DEFAULT unless its comment says\n"
"; otherwise, so a file left exactly as generated behaves as the\n"
"; software does with no config at all.\n"
";\n"
"; SECTION NAMES ARE NAME-AGNOSTIC on purpose: [Midi Settings], not\n"
"; [Vmidi Settings], so this file need not change when program names\n"
"; are settled.\n"
";\n"
"; WHAT IS NOT HERE, deliberately: which image is in each drive (that\n"
"; is state, in /var/lib/vlhe/state/drives), this user's mixer levels and\n"
"; preferences (~/.vlhe/vlhe.conf), the tuning knobs that exist for\n"
"; diagnosis, and the test-harness options.\n"
";\n";

static const char header_user[] =
";\n"
"; vlhe.conf - this user's own settings.\n"
";\n"
"; GENERATED by the control centre, as the machine's file is. Nothing\n"
"; here needs root, and nothing here affects anybody else.\n"
";\n"
"; Mixer levels are the one thing that also appears in the machine's\n"
"; file: that one is a floor applied at boot, and these override it\n"
"; when you log in.\n"
";\n";

static const char header_drives[] =
";\n"
"; drives - which image is in each drive.\n"
";\n"
"; STATE, NOT CONFIGURATION, which is why it is under /var/lib rather\n"
"; than in /etc. The disc daemon maintains it; the control centre asks\n"
"; the daemon rather than writing here itself.\n"
";\n"
"; It is restored at boot, so a machine comes back with the discs it\n"
"; had - no login and no GUI needed.\n"
";\n";

const char *
vlhe_conf_template_header(int file)
{
    switch (file) {
    case VLHE_TPL_USER:   return header_user;
    case VLHE_TPL_DRIVES: return header_drives;
    default:              return header_system;
    }
}

/* ------------------------------------------------------------------ */
/* The table                                                          */
/* ------------------------------------------------------------------ */

const struct vlhe_tpl_entry vlhe_conf_template[] = {

/* --- [Sound Settings] ------------------------------------------- */

{ VLHE_TPL_SYSTEM, "Sound Settings", "LoadAtBoot", "1",
  "; Start the mixer at boot. Almost always 1 - without it nothing else\n"
  "; here works, and a machine that has this installed presumably wants\n"
  "; it. Kept as a setting so it can be turned off without uninstalling.",
  0 },

{ VLHE_TPL_SYSTEM, "Sound Settings", "Include", "1",
  "; Whether the control centre's Load button brings up the mixer.\n"
  "; Its \"Include in load\" box - NOT what boots: that is LoadAtBoot\n"
  "; above, set on Advanced Settings' Startup tab or by setup-vlhe.\n"
  "; Absent, this follows LoadAtBoot.",
  0 },

{ VLHE_TPL_SYSTEM, "Sound Settings", "Channels", "4",
  "; Mixing channels for ordinary clients. A fifth slot is added\n"
  "; separately for the synth.\n"
  ";\n"
  "; NOT A SETTING, AND WRITTEN COMMENTED OUT BECAUSE OF IT.\n"
  "; VSOUND_MAX_CHAN is a compile-time constant in vsound_chan.h, so\n"
  "; editing a value here would have no effect and nothing reads it.\n"
  "; The SETUP PROGRAM is what changes it, by rebuilding the modules.\n"
  ";\n"
  "; FOUR IS DELIBERATE: a game's effects, its music, system sounds and\n"
  "; one spare - more than a 1999 desktop runs at once. Keeping it\n"
  "; constant also keeps VSOUND_MIDI_SLOT fixed at VSOUND_MAX_CHAN, and\n"
  "; vsound_chan.h records a shipped off-by-one from the last time that\n"
  "; index moved.\n"
  ";\n"
  "; An idle slot costs 152 bytes, so the constant is not about memory.\n"
  ";   -> vsound.o VSOUND_MAX_CHAN (compile-time: 4)",
  1 },

{ VLHE_TPL_SYSTEM, "Sound Settings", "MidiChannel", "1",
  "; Reserve a channel for the MIDI synth, so it never competes with the\n"
  "; four above. The synth claims it by opening O_EXCL.\n"
  ";   -> insmod vsound.o vsound_midi=1",
  0 },

{ VLHE_TPL_SYSTEM, "Sound Settings", "Limiter", "1",
  "; What happens when the programs together are louder than the card\n"
  "; can play. 0 = off: the sum is clipped hard. 1 = attack/release:\n"
  "; the whole mix is turned down at once for a loud peak and comes\n"
  "; back up within a fraction of a second. 2 = soft knee: loud\n"
  "; samples are bent smoothly towards full scale, no memory at all.\n"
  ";\n"
  "; ON BY DEFAULT (1), at any channel count, because two programs\n"
  "; at full level overflow the mix. Quiet material passes untouched\n"
  "; in every mode.\n"
  ";   -> insmod vsound.o vsound_limit=N",
  0 },

{ VLHE_TPL_SYSTEM, "Sound Settings", "Attenuation", "100",
  "; A fixed level for the whole mix, in percent - 100 is unchanged,\n"
  "; 71 is about -3 dB, 50 about -6 dB. For a machine where several\n"
  "; loud programs often play at once and the limiter is heard working.\n"
  ";\n"
  "; OFF BY DEFAULT (100). Applied before the limiter.\n"
  ";   -> insmod vsound.o vsound_atten=N",
  0 },

{ VLHE_TPL_SYSTEM, "Sound Settings", "MixRate", "0",
  "; The rate everything is mixed at, in Hz. Every program's audio is\n"
  "; resampled to this before it reaches the card.\n"
  ";\n"
  "; 0 MEANS ASK THE CARD, which is right almost always: the driver\n"
  "; reports what the hardware can really do, and that is what gets\n"
  "; used. A Sound Blaster Pro, for instance, manages 44100 in mono\n"
  "; but only 22050 in stereo, and stereo is what we mix in.\n"
  ";\n"
  "; SET IT ONLY WHERE THE CARD'S OWN ANSWER CANNOT BE TRUSTED. The\n"
  "; one known case is an emu10k1 (SB Live!) with Corel's packaged\n"
  "; driver, which echoes back whatever rate it was asked for without\n"
  "; checking. That chip's output runs at 48000, so:\n"
  ";\n"
  ";     MixRate = 48000\n"
  ";\n"
  "; is both the honest value and the better one - it leaves the\n"
  "; card's own conversion doing nothing instead of resampling twice.\n"
  ";\n"
  "; THE CARD STILL WINS. A rate the hardware cannot do is clamped by\n"
  "; the driver, and the clamped value is what is used - vsoundd says\n"
  "; so when it happens.\n"
  ";   -> vsoundd -S",
  0 },

{ VLHE_TPL_SYSTEM, "Sound Settings", "CardDevice", "",
  "; WHICH CARD YOU WANT TO HEAR - the device vsound plays the mixed\n"
  "; result through.\n"
  ";\n"
  "; EMPTY MEANS DETECT, which is right on a single-card machine.\n"
  "; Set it when only you can know: a machine with more than one\n"
  "; card, where the speakers are plugged into one of them.\n"
  ";\n"
  "; THE CARD IS NOT MOVED OR RELOADED. It keeps its own device node\n"
  "; and its own driver throughout - see ProgramsUse below for how\n"
  "; programs reach the mixer instead.\n"
  ";   -> vsoundd -d",
  0 },

{ VLHE_TPL_SYSTEM, "Sound Settings", "ProgramsUse", "/dev/dsp",
  "; THE DEVICE YOUR PROGRAMS OPEN. This one is pointed at vsound\n"
  "; while the modules are loaded, so anything opening it is mixed\n"
  "; rather than taking the card for itself.\n"
  ";\n"
  "; Programs typically use /dev/dsp. If you have multiple sound\n"
  "; cards, or have set programs to use a different device, name it\n"
  "; here instead.\n"
  ";\n"
  "; WHY IT IS A SEPARATE SETTING FROM CardDevice. They answer\n"
  "; different questions - which name your software opens, and which\n"
  "; card you want to hear - and on a multi-card machine they are\n"
  "; usually different devices. Someone whose player is already\n"
  "; configured for /dev/dsp2 wants THAT redirected; leaving it at\n"
  "; /dev/dsp would mix a device they never open while vsound held\n"
  "; dsp2 and blocked the one they do.\n"
  ";\n"
  "; SETTING BOTH TO THE SAME DEVICE IS ALLOWED and needs no special\n"
  "; handling: the card is given a second name of its own first, so\n"
  "; the pump can still reach it after the redirect.\n"
  ";\n"
  "; IT IS RESTORED ON UNLOAD, to whatever it was - a real device\n"
  "; node or a symlink, with its own target.",
  0 },

{ VLHE_TPL_SYSTEM, "Sound Settings", "ReleaseOnIdle", "0",
  "; Release the card when the last program stops, so the driver's own\n"
  "; teardown runs.\n"
  ";\n"
  "; OFF BY DEFAULT: on a card that does not need it this only adds a\n"
  "; reacquisition risk. Turn it on if the card keeps sounding a tone\n"
  "; or a stuck note after the programs stop.\n"
  ";   -> vsoundd -R",
  0 },

{ VLHE_TPL_SYSTEM, "Sound Settings", "SaveMixerLevels", "0",
  "; Save every sound card's mixer levels - Master, PCM, CD, Mic - when\n"
  "; VLHE unloads (at shutdown, too) and put them back when it loads (at\n"
  "; boot, after the card's driver has set its own defaults).\n"
  ";\n"
  "; OFF BY DEFAULT because nothing on this system has ever done it, so\n"
  "; on would surprise. Levels reset on every module load, not just\n"
  "; every boot, and KMix 1.1 cannot save them at all.\n"
  ";\n"
  "; The levels are the MACHINE's - a card's mixer is shared by every\n"
  "; user - and are kept in their own file, /var/lib/vlhe/mixers (or\n"
  "; `mixers' in a portable folder), one section per card.",
  0 },

{ VLHE_TPL_SYSTEM, "Sound Settings", "SaveProgramLevels", "0",
  "; Keep each program's volume - set on the Volume page or with\n"
  "; `vlhe volume' - across a reload and a reboot: saved when VLHE\n"
  "; unloads, put back when it loads, before any program opens.\n"
  ";\n"
  "; WITHOUT IT a level is still remembered by program name while vsound\n"
  "; stays loaded, so Quake keeps its level across track changes; this\n"
  "; makes the memory outlast the module.\n"
  ";\n"
  "; Per MACHINE, like the mixers - vsound's channels are shared by\n"
  "; every user. Kept in /var/lib/vlhe/volumes (or `volumes' in a\n"
  "; portable folder). OFF BY DEFAULT.",
  0 },

/* --- [Midi Settings] -------------------------------------------- */

{ VLHE_TPL_SYSTEM, "Midi Settings", "LoadAtBoot", "1",
  "; Start the synth daemon at boot. With this 0 the module still\n"
  "; loads, so the MIDI device exists and the daemon can be started\n"
  "; later.",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "Include", "1",
  "; Whether the control centre's Load button brings up the synth.\n"
  "; Its \"Include in load\" box - NOT what boots: that is LoadAtBoot\n"
  "; above, set on Advanced Settings' Startup tab or by setup-vlhe.\n"
  "; Absent, this follows LoadAtBoot.",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "AutoVoices", "1",
  "; Lower the voice limit by itself when the machine cannot render\n"
  "; fast enough, and raise it again when it can - as TiMidity does,\n"
  "; and on by default as there. Never above Voices below. Sending the\n"
  "; daemon SIGUSR1 or SIGUSR2 turns it off until the next start: a\n"
  "; limit set by hand is not moved back.\n"
  ";   -> vmidid -A off (when 0)",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "AutoVoiceDrain", "50",
  "; THE SIX AutoVoice* SETTINGS TUNE AutoVoices above, which works as\n"
  "; TiMidity's does: it watches how full the synth's own output buffer\n"
  "; is, and acts only while that buffer is DRAINING - a machine that\n"
  "; keeps up is never touched. The control centre's Advanced Settings\n"
  "; page sets these; edited here or there, Apply settings on the\n"
  "; Status page gives them to the synth at once, no restart. Fills are\n"
  "; per cent of the buffer, and must keep Emergency < Drain < Healthy,\n"
  "; or the whole set is refused and the defaults used.\n"
  ";\n"
  "; Drain: start reducing while the buffer averages below this and is\n"
  "; not rising. 5-95.\n"
  ";   -> vmidid -a drain=",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "AutoVoiceEmergency", "10",
  "; Emergency: a buffer below this sheds every release tail at once and\n"
  "; lowers the limit to what is left, or to what the machine has shown\n"
  "; it carries, whichever is more. 0-90.\n"
  ";   -> vmidid -a emergency=",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "AutoVoiceHealthy", "75",
  "; Healthy: at or above this, and not falling, the full voice limit\n"
  "; comes back at once. 10-100.\n"
  ";   -> vmidid -a healthy=",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "AutoVoiceSettle", "100",
  "; Settle: milliseconds after acting before acting again, so the\n"
  "; effect can show in the buffer. 20-5000.\n"
  ";   -> vmidid -a settle=",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "AutoVoiceFloor", "16",
  "; Floor: never fewer voices than this. 1-64; 16 is what a Pentium\n"
  "; MMX 233 or a Pentium Pro 133 holds at 22050 Hz with effects on.\n"
  ";   -> vmidid -a floor=",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "AutoVoiceTails", "1",
  "; Tails: 1 lets it end notes that are already fading (their release)\n"
  "; early - quietest first, never drums, over ~10 ms so nothing clicks\n"
  "; - before lowering the limit; 0 only lowers the limit. Notes still\n"
  "; being held are never cut.\n"
  ";   -> vmidid -a tails=",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "DefaultFont0", "",
  "; THE MACHINE'S SoundFont - what the synth loads when nobody has chosen\n"
  "; their own: at BOOT, and for a user with no Font0 of their own.\n"
  "; Bank 0, the General MIDI font. Set by root choosing a font in the\n"
  "; control centre's Midi page (root's choice is the machine's); an\n"
  "; ordinary user's fonts stay theirs. Without it MIDI cannot start\n"
  "; at boot.\n"
  ";   -> vmidid -s FILE@0",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "DefaultFont1", "",
  "; A second machine font, bank 1 - the song's own font in the AWE32\n"
  "; idiom. Usually empty.\n"
  ";   -> vmidid -s FILE@1",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "Voices", "64",
  "; Maximum voices sounding at once, 1 to 512. The synth steals the\n"
  "; quietest when it runs out, which is audible before it is fatal.\n"
  "; Memory follows the number - 512 is about 600 KB - and AutoVoices\n"
  "; above lowers it while the machine cannot keep up.\n"
  ";   -> vmidid -p",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "Gain", "500",
  "; Output gain in thousandths: 1000 is unity, 500 the default.\n"
  "; A whole number - the config holds no fractions.\n"
  ";   -> vmidid -g",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "Reverb", "1",
  "; The reverb: 1 on, 0 off. It is nearly all of the effects' cost,\n"
  "; so off is the first thing to try if the synth cannot keep up - the\n"
  "; chorus below is cheap and can stay on. Its own switch since\n"
  "; 2026-10-05; the two together are vmidid -E.\n"
  ";   -> vmidid -E on|off|reverb|chorus",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "Chorus", "1",
  "; The chorus: 1 on, 0 off - a slight doubling that widens the sound.\n"
  "; Cheap: about a tenth of the effects' cost. Its own switch since\n"
  "; 2026-10-05 (it used to follow Reverb).\n"
  ";   -> vmidid -E on|off|reverb|chorus",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "Law", "0",
  "; The volume curve: 0 is the SoundFont standard, 1 the gentler one\n"
  "; the OPL3 and the original AWE32 used. DOS-era games were balanced\n"
  "; against those cards, so 1 is often the better answer for them.\n"
  ";   -> vmidid -L",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "Filter", "0",
  "; The velocity filter: how hard a note-on maps to brightness.\n"
  ";   -> vmidid -F",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "ModEnv", "1",
  "; The modulation envelope (a voice's pitch or filter sweep). 1, the\n"
  "; default, is FAST: a voice whose envelope sweeps nothing skips it and\n"
  "; catches up exactly the moment it starts to - about 7% less synth\n"
  "; work, and identical to 0 on everything tested. 0 is REFERENCE: every\n"
  "; voice steps it every sample, as the SoundFont spec describes.\n"
  ";   -> vmidid -M reference|fast",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "Rate", "44100",
  "; The synth's sample rate. THE MOST EFFECTIVE SETTING ON A SLOW\n"
  "; MACHINE, because it changes the DEADLINE and not just the work:\n"
  "; a 256-frame block is 5 ms of wall clock at 44100 and 11 ms at\n"
  "; 22050. On a slow machine that is the difference between constant\n"
  "; dropouts and none. Try this before turning effects off.\n"
  ";   -> vmidid -r",
  0 },

{ VLHE_TPL_SYSTEM, "Midi Settings", "ChannelRelease", "3000",
  "; Milliseconds of silence before the synth lets its sound channel\n"
  "; go, so the card can be released between songs (Sound Settings'\n"
  "; ReleaseOnIdle). Silence means no note sounding AND the reverb\n"
  "; and chorus faded to nothing, so a short value no longer cuts a\n"
  "; song's last chord off mid-decay. Shorter frees the card sooner;\n"
  "; the first note after a release is ~100 ms late while the card\n"
  "; is reopened, so it should outlast any rest inside a piece.\n"
  "; 0 holds the channel for as long as the synth runs.\n"
  ";   -> vmidid -R",
  0 },

/* --- [CD Settings] ---------------------------------------------- */

{ VLHE_TPL_SYSTEM, "CD Settings", "LoadAtBoot", "1",
  "; Start the disc daemons at boot. With this 0 the module still\n"
  "; loads, so the drives exist and images can be attached later by\n"
  "; hand or by the control centre.",
  0 },

{ VLHE_TPL_SYSTEM, "CD Settings", "Include", "1",
  "; Whether the control centre's Load button brings up the disc daemons.\n"
  "; Its \"Include in load\" box - NOT what boots: that is LoadAtBoot\n"
  "; above, set on Advanced Settings' Startup tab or by setup-vlhe.\n"
  "; Absent, this follows LoadAtBoot.",
  0 },

{ VLHE_TPL_SYSTEM, "CD Settings", "Drives", "1",
  "; How many virtual drives to create. ONE is the default and the\n"
  "; normal case; each extra drive costs a device node and clutters\n"
  "; what the desktop shows, so a user who wants more says so. The\n"
  "; ceiling is 8.\n"
  ";   -> insmod vdisc.o vdisc_ndevs=N",
  0 },

{ VLHE_TPL_SYSTEM, "CD Settings", "DrivesAutoLoad", "1",
  "; Reattach, when the disc server starts, each drive marked \"Load at\n"
  "; startup\" on the CD page - its image as recorded in\n"
  "; /var/lib/vlhe/state/drives (or `drives' in a portable folder), at boot\n"
  "; or at Load. 0: every drive starts empty, whatever the boxes say.\n"
  "; Separate from LoadAtBoot: a user may want the drives present but\n"
  "; no disc in them.\n"
  ";   -> vdiscd -r",
  0 },

{ VLHE_TPL_SYSTEM, "CD Settings", "Major", "63",
  "; Block major number. 60-63 are the kernel's LOCAL/EXPERIMENTAL\n"
  "; range (devices.txt:1005), reserved for devices with no official\n"
  "; number - which is exactly us, and what the reference\n"
  "; implementation uses.\n"
  ";\n"
  "; 44 was the old default and was never ours: it belongs to Flash\n"
  "; Translation Layer filesystems, and was borrowed rather than\n"
  "; allocated.\n"
  ";   -> insmod vdisc.o vdisc_major=N",
  0 },

/* --- [Tracing] --------------------------------------------------- */

{ VLHE_TPL_SYSTEM, "Tracing", "Enabled", "0",
  "; Diagnostic tracing, for a bug report. 0 is off and is right for\n"
  "; normal use. The next load then traces, so a problem can be shown\n"
  "; without rebuilding anything:\n"
  ";\n"
  ";   1  EVENTS - opens, closes, settings, refusals, the limiter once\n"
  ";      a second, the synth's -v report. What a test reads.\n"
  ";   2  EVERYTHING - also every CD data read and every MIDI byte.\n"
  ";      Very large: one CD run wrote 183,000 lines.\n"
  ";\n"
  "; The trace goes to the modules' own rings - 2048 lines each, read\n"
  "; through /proc/vsound-trace, /proc/vmidi-trace, /proc/vdisc-trace\n"
  "; (`cat' one, or `vlhe trace' for all three in time order) - and\n"
  "; NEVER to the system log; the kernel log keeps errors and the\n"
  "; one-time lines only. It grows while it is on: turn it off after.\n"
  ";   -> 1: vsound_trace=1 vsound_rate_mix=0 vsound_rate_write=0\n"
  ";      vsound_rate_life=1, vmidi_trace=1, vdisc_trace=1, vmidid -v\n"
  ";   -> 2: as 1, plus vmidi_rate_byte=1 and vdisc_trace=2",
  0 },

{ VLHE_TPL_SYSTEM, "Tracing", "Capture", "0",
  "; With Enabled above, put each load's trace in its own folder,\n"
  "; run-<date-time>/trace.log, beside DAEMON.LOG - which is copied in\n"
  "; at unload. For testing. OFF BY DEFAULT. It starts `vlhe trace'\n"
  "; as the reader with the load and stops it before the unload's\n"
  "; rmmods; it stops no service and needs no root. Without it the\n"
  "; rings are still there to read by hand while the modules are\n"
  "; loaded.\n"
  ";   -> run-<stamp>/trace.log, trace.pid, trace.dir beside DAEMON.LOG",
  0 },

/* --- [Boot] ------------------------------------------------------ */

{ VLHE_TPL_SYSTEM, "Boot", "FinishLeftover", "1",
  "; After a power loss or a crash while VLHE was loaded, the changes it\n"
  "; made are still on record. 1: the boot puts them back first - only\n"
  "; what VLHE recorded making, never a path someone changed since - and\n"
  "; loads VLHE if that worked; the next time the control centre or\n"
  "; `vlhe status' is run it says what was done. 0: the boot only notes\n"
  "; it, and VLHE stays unloaded until you finish it (`vlhe apply -u',\n"
  "; or Finish the unload on the Status page). Installed copies only -\n"
  "; a portable copy does not run at boot.\n"
  ";   -> vlhe apply --boot, from the init script",
  0 },

/* --- [Load] ------------------------------------------------------ */

{ VLHE_TPL_SYSTEM, "Load", "BaselineDrift", "ask",
  "; When a device file VLHE manages (/dev/dsp, /dev/cdrom, ...) has\n"
  "; changed since the baseline was recorded - and VLHE did not change\n"
  "; it - what a Load from the control centre or `vlhe apply' does:\n"
  ";   ask     ask what to do: undo the change, accept it as the new\n"
  ";           baseline, load anyway, or cancel (the default)\n"
  ";   warn    keep the baseline, leave the change, load, and say so\n"
  ";   refuse  stop the Load with nothing changed, and say why\n"
  "; There is deliberately no \"accept\": the baseline is only replaced\n"
  "; when someone chooses it. The boot always warns - no one is there to\n"
  "; answer. The control centre's Advanced Settings page sets this.",
  0 },

/* --- the user's own file ----------------------------------------- */

{ VLHE_TPL_USER, "Interface", "Font", "",
  "; The control centre's font, as a full X font name (XLFD) - the\n"
  "; File / Preferences picker writes one. Empty means GTK's own\n"
  "; default, which is what Corel's theme leaves in place.\n"
  ";\n"
  ";   Font = -adobe-helvetica-medium-r-normal-*-12-*-*-*-p-*-iso8859-1\n"
  ";\n"
  "; THE SIZE IS PART OF IT - field 7, the 12 above. There is no\n"
  "; separate size key; two places to say one thing can disagree.",
  0 },

/*
 * THE REST OF [Interface] FOLLOWS Font DIRECTLY - 2026-10-01. These
 * three sat after the [CDG Viewer] block, and format_file() writes a
 * section header only the FIRST time it meets a section, so they were
 * written under [CDG Viewer], read back as that section's keys, and
 * never found by their readers: VerticalSliders=1 was saved on every
 * Save and the faders came up horizontal on every start. ONE
 * CONTIGUOUS RUN PER SECTION is the rule, and test_vlhe_conf_template
 * now asserts it. vlhe_backend.c's load_config() moves the strays an
 * older file carries.
 */
{ VLHE_TPL_USER, "Interface", "StartPage", "0",
  "; Which page the window opens on, and where OK returns to:\n"
  ";   0 Status   1 Volume   2 Sound   3 MIDI   4 CD   5 CD+G Viewer\n"
  ";   6 Render MIDI\n"
  "; Status is the default because a fresh install is when something\n"
  "; is most likely wrong, and that page says so. Volume is the one\n"
  "; most people will want.",
  0 },

{ VLHE_TPL_USER, "Interface", "VerticalSliders", "0",
  "; Draw the volume faders vertically, as a hardware mixer does,\n"
  "; rather than as horizontal bars.",
  0 },

{ VLHE_TPL_USER, "Interface", "ShowApplyResult", "",
  "; Show a box listing every step after Load or Unload, with what\n"
  "; succeeded and what did not.\n"
  ";\n"
  ";   (empty)  the default for this copy - ON when running from an\n"
  ";            unpacked folder, OFF when installed\n"
  ";   1        always show it\n"
  ";   0        never show it\n"
  ";\n"
  "; THE DEFAULT DIFFERS BY MODE ON PURPOSE. Someone running a\n"
  "; portable copy is finding out what the program does, and a status\n"
  "; line saying so is gone the moment anything else writes there.\n"
  "; Someone who installed it already knows, and a box after every\n"
  "; Load becomes something to dismiss.\n"
  ";\n"
  "; EMPTY IS NOT THE SAME AS 0. A portable user who turns this off\n"
  "; writes 0, and that must survive - which it could not if the\n"
  "; absent value and the off value were the same.",
  0 },

/*
 * RENDER SETTINGS - the control centre's Render MIDI page, Advanced
 * tab. PER-USER, like the Interface block above, because they
 * describe how one person likes their renders and not how the
 * machine plays.
 *
 * NONE OF THESE CHANGE THE SYNTH. The daemon reads `Midi Settings';
 * these reach `smf2wav' and nothing else, which is what the page
 * says on it. UseVlheSettings decides which set a render uses.
 */
/*
 * WHERE THE INSTALLER PUT THE MODULES - and its PRESENCE is what
 * says this machine is installed rather than on trial.
 *
 * THE GUI USED TO ASK THE WRONG QUESTION. It probed for vsound.o
 * beside the binary and in /lib/modules/<uname -r>/misc, and called
 * the first "trial mode" - which on 86Box 2026-09-22 meant running
 * the GUI out of /mnt/xfer offered to create ./vlhe-user.conf on a
 * machine whose user already had ~/.vlhe/vlhe.conf. Where a binary
 * was launched from is not a fact about the machine.
 *
 * ONLY THE INSTALLER KNOWS, so the installer writes it. One key
 * answers both questions - IS this installed, and WHERE are the
 * modules - so `vlhe apply' stops guessing as well.
 *
 * EMPTY MEANS NOT INSTALLED, which is the trial case and is the
 * default here: a config that has never been through setup-vlhe
 * describes a machine that has never been installed.
 *
 * CORRECTED 2026-10-03 (design/54 T14): THAT ROLE IS GONE, and since
 * design/55 13f (2026-10-04) installed versus portable is decided when
 * the program is BUILT (vlhe_self_is_trial()), not by any file. setup-vlhe
 * does not write this key (design/54 L05). What remains is the module
 * location FOR AN INSTALLED VLHE - and since 2026-10-05 NOT EVEN THAT:
 * the installed load is `modprobe NAME', which finds the running
 * kernel's own copy, and the plan no longer reads this key
 * (vlhe_apply.c module_dir_find()). Kept in the template so a file that
 * has it is described rather than surprising.
 */
{ VLHE_TPL_SYSTEM, "Paths", "ModuleDir", "",
  "; Not read. An installed VLHE loads its modules with modprobe,\n"
  "; which finds the running kernel's own in /lib/modules/<kernel>/misc,\n"
  "; so a machine booting more than one 2.2.16 loads the right one. A\n"
  "; portable VLHE uses its own modules folder.",
  0 },

{ VLHE_TPL_USER, "Render Settings", "UseVlheSettings", "1",
  "; 1 renders with the Midi Settings, so the file sounds like the\n"
  "; machine plays it. 0 uses the values below.",
  0 },

{ VLHE_TPL_USER, "Render Settings", "Voices", "512",
  "; Maximum voices for an OFFLINE render: 1 to 2048. Not the\n"
  "; synth's 64 - rendering has no deadline to miss, so a busy file\n"
  "; can have every note it asks for. More voices, longer render.\n"
  ";   -> smf2wav -p",
  0 },

{ VLHE_TPL_USER, "Render Settings", "Rate", "44100",
  "; Sample rate of the rendered file.\n"
  ";   -> smf2wav -r",
  0 },

{ VLHE_TPL_USER, "Render Settings", "Gain", "500",
  "; Master gain in thousandths: 1000 is unity, 2000 the maximum.\n"
  "; The output clips and counts whatever does not fit. A whole\n"
  "; number - the config holds no fractions.\n"
  ";   -> smf2wav -g",
  0 },

{ VLHE_TPL_USER, "Render Settings", "Law", "0",
  "; Volume curve: 0 spec (SoundFont standard, (v/127)^2), 1 linear\n"
  "; (gentler, Sound Blaster era).\n"
  ";   -> smf2wav -L",
  0 },

{ VLHE_TPL_USER, "Render Settings", "Filter", "0",
  "; Velocity-filter default: 0 awe, 1 SoundFont 2.01, 2 SoundFont\n"
  "; 2.04, 3 none.\n"
  ";   -> smf2wav -F",
  0 },

{ VLHE_TPL_USER, "Render Settings", "Reverb", "1",
  "; The reverb for a render, 1 on, 0 off - as [Midi Settings] Reverb.\n"
  ";   -> smf2wav -E on|off|reverb|chorus",
  0 },

{ VLHE_TPL_USER, "Render Settings", "Chorus", "1",
  "; The chorus for a render, 1 on, 0 off - as [Midi Settings] Chorus.\n"
  ";   -> smf2wav -E on|off|reverb|chorus",
  0 },

{ VLHE_TPL_USER, "Render Settings", "Bypass", "0",
  "; Skip the low-pass filter where its cutoff is above anything the\n"
  "; sample carries.\n"
  ";   -> smf2wav -B",
  0 },

{ VLHE_TPL_USER, "Render Settings", "ModEnv", "1",
  "; The modulation envelope, as [Midi Settings] ModEnv: 1 fast (the\n"
  "; default), 0 reference - identical on everything tested.\n"
  ";   -> smf2wav -M reference|fast",
  0 },

{ VLHE_TPL_USER, "Render Settings", "GmFont", "",
  "; The General MIDI font a render uses when UseVlheSettings is 0.\n"
  "; Empty means the Midi Settings' own.",
  0 },

{ VLHE_TPL_USER, "Render Settings", "SongFont", "",
  "; A song font for bank 1, or empty for none.",
  0 },

{ VLHE_TPL_USER, "Render Settings", "WavTemp", "0",
  "; Where the temporary WAV goes during an MP3 render - it is ten\n"
  "; times the MP3. 0 = whichever of /tmp and the output's folder has\n"
  "; more free space, 1 = always /tmp, 2 = always beside the output.",
  0 },

{ VLHE_TPL_USER, "CDG Viewer", "Zoom", "2",
  "; The CD+G picture's scale: 1 or 2. Native is 300x216, so 2 gives\n"
  "; 600x432 and fills the pane. INTEGER ONLY - CD+G draws 6x12 tiles\n"
  "; and a fractional scale blurs them.",
  0 },

{ VLHE_TPL_USER, "CDG Viewer", "Anchor", "5",
  "; Where the picture sits in the space above the controls, as a\n"
  "; numpad cell:\n"
  ";\n"
  ";     7  8  9      top-left     top-centre     top-right\n"
  ";     4  5  6      centre-left  centre         centre-right\n"
  ";     1  2  3      bottom-left  bottom-centre  bottom-right\n"
  ";\n"
  "; THE CONTROLS DO NOT MOVE - the transport row and the information\n"
  "; line stay at the bottom of the page and only the picture is\n"
  "; placed. Detached, only the COLUMN is read (7/4/1 left, 8/5/2\n"
  "; centre, 9/6/3 right), because the floating window is sized to\n"
  "; its contents and has no vertical slack.",
  0 },

{ VLHE_TPL_USER, "CDG Viewer", "TrackFormat", "0",
  "; What the track dropdown shows:\n"
  ";   0  the title alone      01: Song of Joy\n"
  ";   1  artist and title     01: Felix and The Purrs - Song of Joy\n"
  "; 1 is for a compilation, where every track has a different\n"
  "; performer. CDDB could not express that at all - it carries one\n"
  "; artist for the whole disc - so this needs CD-TEXT or a CUE that\n"
  "; names a PERFORMER per track.",
  0 },

{ VLHE_TPL_USER, "CDG Viewer", "InfoFields", "performer,title",
  "; Which CD-TEXT fields appear in the line under the picture, and\n"
  "; IN WHAT ORDER - the list is read left to right and shown that\n"
  "; way, separated by dashes. An absent field is skipped rather than\n"
  "; leaving a gap.\n"
  ";\n"
  "; Any of: title performer songwriter composer arranger message\n"
  ";         track time\n"
  ";\n"
  "; There is room for ONE line at Zoom=2 - about 86 characters - so a\n"
  "; long list will be truncated. Zoom=1 leaves room for more.",
  0 },

{ VLHE_TPL_USER, "CDG Viewer", "BorderMask", "1",
  "; Hide the outer tile of the picture, as a CD+G player does. The\n"
  "; margin behind it holds artwork waiting to scroll into view;\n"
  "; showing it reveals content a moment early.",
  0 },

{ VLHE_TPL_USER, "CDG Viewer", "ClearOnEject", "1",
  "; Clear the picture when the disc is ejected. 0 keeps the last\n"
  "; frame on screen until the next disc paints over it, as a\n"
  "; player's screen does.",
  0 },

{ VLHE_TPL_USER, "CDG Viewer", "Drive", "0",
  "; Which virtual drive the CD+G viewer shows and plays: 0 is\n"
  "; /dev/vdisc0. Chosen on the CD page when there is more than one\n"
  "; drive. If it holds no disc with audio, the viewer uses the first\n"
  "; drive that does.",
  0 },

{ VLHE_TPL_USER, "CDG Viewer", "FollowAnyDisc", "1",
  "; 1: when the chosen drive has no disc with audio, the viewer uses\n"
  "; the first drive that does. 0: the chosen drive only - the viewer\n"
  "; shows no disc until one goes in it or another is chosen.",
  0 },

{ VLHE_TPL_USER, "CDG Viewer", "StopOnSwap", "0",
  "; 1: choosing another drive stops the disc the viewer was playing.\n"
  "; 0: it plays on, as a second CD player would. A disc started from\n"
  "; KsCD is never stopped by this.",
  0 },

{ VLHE_TPL_USER, "CDG Viewer", "CompactDetached", "0",
  "; When the viewer is detached, put Attach and the track list on a\n"
  "; second row under the player controls: a narrower window, one\n"
  "; row taller.",
  0 },

{ VLHE_TPL_USER, "Fonts", "Search", "",
  "; Extra directories to look in for SoundFonts, separated by colons.\n"
  "; These are searched BEFORE the three built-in ones, so a font you\n"
  "; put somewhere deliberately wins over one of the same name in a\n"
  "; system directory.",
  0 }
};

const int vlhe_conf_template_n =
    (int)(sizeof vlhe_conf_template / sizeof vlhe_conf_template[0]);

/* ------------------------------------------------------------------ */
/* Using it                                                           */
/* ------------------------------------------------------------------ */

int
vlhe_conf_template_defaults(struct vlhe_conf *c, int file)
{
    int i, n = 0;

    c->n = 0;
    for (i = 0; i < vlhe_conf_template_n; i++) {
        if (vlhe_conf_template[i].file != file)
            continue;
        if (vlhe_conf_template[i].disabled)
            continue;           /* documented, but not a live key */
        if (vlhe_conf_set(c, vlhe_conf_template[i].section,
                          vlhe_conf_template[i].key,
                          vlhe_conf_template[i].dflt) < 0)
            break;
        n++;
    }
    return n;
}

/* Has this section already been opened in the output? */
static int
seen_section(const char *const *seen, int nseen, const char *section)
{
    int i;

    for (i = 0; i < nseen; i++) {
        if (strcmp(seen[i], section) == 0)
            return 1;
    }
    return 0;
}

/* Format the whole file into `fp'.
 *
 * WRITTEN STRAIGHT TO THE STREAM, NOT INTO A BUFFER. The first version
 * built the text in a fixed `char body[]' and stopped when it filled -
 * SILENTLY, producing a valid-looking file that had lost 22 of its 23
 * keys. The test caught it, and the fix is to have no size to
 * overrun: the comments alone are several thousand bytes and a bound
 * that has to be maintained by hand is a bound that will be wrong
 * again. */
static int
format_file(FILE *fp, const struct vlhe_conf *c, int file)
{
    const char *seen[VLHE_CONF_MAX_ENTRIES];
    int nseen = 0;
    int i, j;
    int written[VLHE_CONF_MAX_ENTRIES];

    for (i = 0; i < c->n; i++)
        written[i] = 0;

    /* Template order first, each key under its section header with its
     * comment above it. */
    for (i = 0; i < vlhe_conf_template_n; i++) {
        const struct vlhe_tpl_entry *t = &vlhe_conf_template[i];
        const char *value;
        int found = -1;

        if (t->file != file)
            continue;

        for (j = 0; j < c->n; j++) {
            if (strcmp(c->entry[j].section, t->section) == 0 &&
                strcmp(c->entry[j].key, t->key) == 0) {
                found = j;
                break;
            }
        }
        value = found >= 0 ? c->entry[found].value : t->dflt;

        if (!seen_section(seen, nseen, t->section)) {
            if (nseen < VLHE_CONF_MAX_ENTRIES)
                seen[nseen++] = t->section;
            if (fprintf(fp, "\n[%s]\n", t->section) < 0)
                return -1;
        }

        if (t->comment != NULL) {
            if (fprintf(fp, "\n%s\n", t->comment) < 0)
                return -1;
        }

        if (fprintf(fp, "%s%s = %s\n",
                    t->disabled ? "; " : "", t->key, value) < 0)
            return -1;

        if (found >= 0)
            written[found] = 1;

        /* IS THIS THE TEMPLATE'S LAST KEY IN THIS SECTION? If so, any
         * of the user's keys that belong here go NOW, under this
         * header - not at the end of the file, where they would land
         * beneath whichever section happened to be written last and
         * read back as part of it. A retired key quietly changing
         * section is a setting silently moved. */
        {
            int more = 0;

            for (j = i + 1; j < vlhe_conf_template_n; j++) {
                if (vlhe_conf_template[j].file == file &&
                    strcmp(vlhe_conf_template[j].section,
                           t->section) == 0) {
                    more = 1;
                    break;
                }
            }
            if (!more) {
                for (j = 0; j < c->n; j++) {
                    if (written[j])
                        continue;
                    if (strcmp(c->entry[j].section, t->section) != 0)
                        continue;
                    if (fprintf(fp, "%s = %s\n",
                                c->entry[j].key, c->entry[j].value) < 0)
                        return -1;
                    written[j] = 1;
                }
            }
        }
    }

    /* WHOLE SECTIONS THE TEMPLATE DOES NOT KNOW, kept rather than
     * dropped - a key we stopped recognising is still the user's.
     * Keys in a section the template DOES know were already emitted
     * under their own header, above. */
    for (j = 0; j < c->n; j++) {
        if (written[j])
            continue;
        if (!seen_section(seen, nseen, c->entry[j].section)) {
            if (nseen < VLHE_CONF_MAX_ENTRIES)
                seen[nseen++] = c->entry[j].section;
            if (fprintf(fp, "\n[%s]\n", c->entry[j].section) < 0)
                return -1;
        }
        if (fprintf(fp, "%s = %s\n",
                    c->entry[j].key, c->entry[j].value) < 0)
            return -1;
    }

    return 0;
}

int
vlhe_conf_template_write(const struct vlhe_conf *c, const char *path,
                         int file, int backup)
{
    return vlhe_conf_write_fn(path, vlhe_conf_template_header(file),
                              format_file, c, file, backup);
}
