/*
 * cddb.h - the disc id, and the records other players have cached.
 *
 * Copyright (c) 2026 Thomas Tranter
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Part of VLHE. See LICENSE for the full license text.
 *
 * WE DO NOT TALK TO A SERVER, AND THAT IS THE DESIGN - the user's,
 * 2026-09-26: *"do our CDDB by just looking it up in the cddb
 * caches"*.
 *
 * KsCD AND grip BOTH CACHE WHAT THEY FETCH, in the same file format
 * and under the same name - the disc id in hex. So a disc the user
 * has already looked up in either player has its titles sitting on
 * this machine, and reading them costs no socket, no protocol, no
 * timeout, and cannot hang a GUI on a machine with no route.
 *
 * WHAT IT COSTS THE USER: the lookup must have happened SOMEWHERE
 * first. This is not a lookup feature - it is "use what is already
 * known". A disc nobody has fetched shows <Unknown>, exactly as it
 * does today.
 *
 * AND IT IS A STRICT SUBSET OF THE REAL THING. If a network client
 * is ever wanted, the disc id and this parser are the parts it
 * needs anyway; only the socket would be new.
 *
 * ------------------------------------------------------------------
 * WHERE THE RECORDS ARE, read from both players' source:
 *
 *   KsCD    /usr/X11R6/share/apps/kscd/cddb/<genre>/<discid>
 *           (`cddb.cpp:652', and `kscdrc' names the base directory
 *           as LocalBaseDir. COREL SHIPS THE GENRE DIRECTORIES -
 *           misc, rock, jazz, classical, data and the rest, all
 *           dated 17-Jul-2000 - so the layout exists on a machine
 *           where KsCD has never run.)
 *
 *   grip    ~/.cddb/<discid>, falling back to ~/.cddb/<genre>/<discid>
 *           (`cddb.c:532' and `:591'. It tries the FLAT path first,
 *           which KsCD does not.)
 *
 * BOTH HOMES ARE SEARCHED, the caller's and root's, because a record
 * fetched by one user is invisible to the other and on these
 * machines the GUI may run as either.
 *
 * ------------------------------------------------------------------
 * THE FORMAT is xmcd, which is the CDDB protocol's reply written to
 * a file - so one parser serves a cache hit and a future network
 * reply identically:
 *
 *     # xmcd CD database file generated by grip 2.91
 *     DISCID=9d0e790b
 *     DTITLE=Trent Reznor / Quake
 *     TTITLE0=[data track]
 *     TTITLE1=Quake Theme
 *     EXTD=
 *     PLAYORDER=
 *
 * `DTITLE' IS "artist / title" IN ONE FIELD, which is the whole of
 * CDDB's artist support: there is NO PER-TRACK ARTIST. A compilation
 * gets one disc artist and a list of song names. That is why CD-TEXT
 * wins where both exist (`design/34' 6d) - it has PERFORMER at track
 * level and CDDB cannot express it at all.
 *
 * grip WRITES TWO NON-STANDARD LINES behind a flag, `DYEAR=' and
 * `DGENRE=' (`cddb.c:712'). Unknown keys are ignored rather than
 * refused, so those cost nothing.
 *
 * C89, GCC 2.95.2.
 */

#ifndef VLHE_CDDB_H
#define VLHE_CDDB_H

#include "cdtext.h"

/*
 * THE DISC ID. The algorithm is FIXED BY COMPATIBILITY - workman's
 * own comment, carried into KsCD (`cdrom.c:112'): "For backward
 * compatibility this algorithm must not change".
 *
 *   sum the decimal digits of each track's start in SECONDS
 *   t = lead-out seconds - first track seconds
 *   id = (n % 0xff) << 24 | t << 8 | ntracks
 *
 * `starts' and `leadout' are LBAs as this project holds them:
 * FILE-RELATIVE, with no lead-in. THE +150 IS ADDED HERE, because
 * the algorithm works in absolute MSF where sector 0 is 00:02:00 -
 * and getting that wrong shifts every seconds value by two and
 * produces a plausible id that matches nothing.
 *
 * Verified against a disc whose id is known: the Information
 * Society CloneCD set in ExampleCDs/ is `750a540a', recorded in
 * design/27 section 4a from a live gnudb query that returned an
 * exact match.
 */
unsigned long vlhe_cddb_discid(const int *starts, int ntracks, int leadout);

/*
 * PARSE AN xmcd RECORD into a cdtext struct, so the caller renders
 * one shape whatever the source.
 *
 * `DTITLE=artist / title' fills the DISC's performer and title;
 * `TTITLEn' fills each track's title and NOTHING ELSE, since CDDB
 * has no per-track artist.
 *
 * SETS `present' only when a DISCID or a DTITLE was seen, so a
 * truncated or empty file reads as "no record" rather than as a
 * disc with blank names.
 *
 * 0 on success, -1 when the file cannot be read or holds no record.
 */
int vlhe_cddb_parse_file(const char *path, struct cdtext *out);

/*
 * FIND AND PARSE A CACHED RECORD for this disc id, looking in every
 * place KsCD or grip may have left one.
 *
 * VLHE_CDDB_DIRS overrides the search path for the host test - a
 * colon-separated list of base directories, checked instead of the
 * built-in ones.
 *
 * 0 when a record was found and parsed, -1 otherwise.
 */
int vlhe_cddb_lookup(unsigned long discid, struct cdtext *out);

#endif /* VLHE_CDDB_H */
